<a href="https://colab.research.google.com/github/pnggkkm/Python-Programming/blob/main/Array_Indexing_and_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Indexing**
Array indexing in NumPy refers to accessing individual elements or groups of elements within an array.

**Array Indexing**
Array indexing in NumPy refers to accessing individual elements or groups of elements within an array.
indexing commonly used in NumPy arrays:

**Basic Indexing:** Accessing individual elements of an array using integer indices.

**Slicing:** Extracting a subset of elements from an array by specifying a range of indices.

**Boolean Indexing:** Selecting elements based on a boolean condition.

**Fancy Indexing:** Accessing multiple elements at once using arrays of indices.

**Reverse Indexing:** Accessing elements from the end of an array using negative indices.

Understanding and effectively utilizing these indexing techniques is essential for working efficiently with NumPy arrays and manipulating data according to specific requirements.

**Basic Indexing:**

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Access the element at index 2
print(arr[2])  # Output: 3


3


**Boolean Indexing:**

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Boolean indexing to select elements greater than 2
print(arr[arr > 2])  # Output: [3 4 5]


[3 4 5]


**Fancy Indexing:**

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Fancy indexing to select elements at indices 1 and 3
print(arr[[1, 3, 4]])  # Output: [2 4]


[2 4 5]


 **Reverse Indexing**
 arrays in NumPy support reverse indexing, similar to Python lists. Reverse indexing allows you to access elements from the end of the array using negative indices.

For example, given an array arr, you can access the last element using -1, the second-to-last element using -2, and so on.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Access the last element
print(arr[-1])  # Output: 5

# Access the second-to-last element
print(arr[-2])  # Output: 4


5
4


**Slicing**
Array slicing in NumPy refers to extracting a subset of elements from an array based on specified indices or ranges. It allows you to create views of the original array without making a copy, which is useful for efficiently working with large datasets.

**1D Arrays:**
To slice a 1D array, you specify the start, stop, and step indices using the syntax array[start:stop:step].
If you omit the start index, it defaults to 0. If you omit the stop index, it defaults to the end of the array. If you omit the step, it defaults to 1.

In [12]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Slice from index 2 to 6 (exclusive) with a step of 2
print(arr[2:6:2])  # Output: [2 4]


[2 4]


In [13]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[2:6])

[2 3 4 5]


**2D Arrays:**
For 2D arrays, you specify the row and column ranges separated by a comma.
You can also use slicing to extract entire rows or columns.

In [14]:
import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

# Slice rows 1 to 2 (exclusive) and columns 0 to 2 (exclusive)
print(arr[1:2, 0:2])  # Output: [[3 4]]

# Extract the second column
print(arr[:, 1])  # Output: [1 4 7]


[[3 4]]
[1 4 7]


**Indexing in multidimensional arrays**
Indexing in multidimensional arrays in NumPy allows you to access individual elements, rows, columns, or subarrays using indices. Each dimension of the array has its own index, separated by commas.

In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access element at row 1, column 2
print(arr[1, 2])  # Output: 6


6


**Accessing a Row or Column:**

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access the second row
print(arr[1])  # Output: [4 5 6]

# Access the third column
print(arr[:, 2])  # Output: [3 6 9]


[4 5 6]
[3 6 9]


**Accessing a Subarray:**

In [11]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access a 2x2 subarray from the top-left corner
print(arr[:2, :2])  # Output: [[1 2]
                    #          [4 5]]

# Access a 2x2 subarray from the bottom-right corner
print(arr[1:, 1:])  # Output: [[5 6]
                    #          [8 9]]


[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


**Using Slicing with Steps:**

In [15]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access every other element in the first row
print(arr[0, ::2])  # Output: [1 3]

# Access every other row and every other element in those rows
print(arr[::2, ::2])  # Output: [[1 3]
                       #          [7 9]]


[1 3]
[[1 3]
 [7 9]]


**Using Negative Indices:**

In [16]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access the last element in the last row
print(arr[-1, -1])  # Output: 9


9
