<a href="https://colab.research.google.com/github/pnggkkm/Python-Programming/blob/main/Array_operations_and_attributes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Array Operations**

**Arithmetic Operations**

**Element-wise Addition:**

Element-wise addition of two vectors is a simple operation where corresponding elements from each vector are added together to produce a new vector.

For example, if you have two vectors u = [1, 2] and v = [3, 4], the element-wise addition would be calculated as follows:

The first element of u (1) is added to the first element of v (3), resulting in the first element of the result vector (4).
The second element of u (2) is added to the second element of v (4), resulting in the second element of the result vector (6).
So, the result of element-wise addition of u and v would be [4, 6]. Each element in the result vector is the sum of the corresponding elements in the input vectors. This operation can be performed efficiently in NumPy using the + operator on the NumPy arrays representing the vectors.

In [ ]:
import numpy as np

u = np.array([1, 2])
v = np.array([3, 4])

# Element-wise addition
result = u + v
print(result)
# Output: [4 6]


[4 6]


**Element-wise Subtraction:**

In [ ]:
import numpy as np

u = np.array([1, 2])
v = np.array([3, 4])

# Element-wise subtraction
result = u - v
print(result)
# Output: [-2 -2]


[-2 -2]


**Element-wise Multiplication:**

In [ ]:
import numpy as np

u = np.array([1, 2])
v = np.array([3, 4])

# Element-wise multiplication
result = u * v
print(result)
# Output: [3 8]


[3 8]


**Element-wise Division:**

In [ ]:
import numpy as np

u = np.array([10, 20])
v = np.array([2, 4])

# Element-wise division
result = u / v
print(result)

[5. 5.]


**Dot Product**

The dot product of two vectors is a mathematical operation that takes two vectors and returns a scalar. It is also known as the scalar product or inner product. The dot product is calculated by multiplying the corresponding elements of the two vectors and then summing up the products.

For example, if you have two vectors u = [1, 2, 3] and v = [4, 5, 6], the dot product would be calculated as follows:

Multiply the first element of u (1) with the first element of v (4), and add it to the product of the second element of u (2) and the second element of v (5), and finally add the product of the third element of u (3) and the third element of v (6).
Mathematically, this is expressed as: 1*4 + 2*5 + 3*6 = 4 + 10 + 18 = 32.
So, the dot product of u and v is 32. In general, the dot product of two vectors u and v of the same length n is calculated as:

u⋅v=u
1
​
 ×v
1
​
 +u
2
​
 ×v
2
​
 +…+u
n
​
 ×v
n
​


The dot product is useful in many areas of mathematics and physics, including geometry, mechanics, and signal processing. In NumPy, you can calculate the dot product of two arrays using the numpy.dot() function .

In [ ]:
import numpy as np

u = np.array([1, 2])
v = np.array([3, 4])

# Dot product
result = np.dot(u, v)
print(result)
# Output: 11


11


**More Examples of Arithmetic Operations**



In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
result = arr1 + arr2
print(result)
# Output:
# [[ 6  8]
#  [10 12]]


[[ 6  8]
 [10 12]]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise subtraction
result = arr1 - arr2
print(result)
# Output:
# [[-4 -4]
#  [-4 -4]]


[[-4 -4]
 [-4 -4]]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise multiplication
result = arr1 * arr2
print(result)
# Output:
# [[ 5 12]
#  [21 32]]


[[ 5 12]
 [21 32]]


**Scalar Operations**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Element-wise addition
result = arr + 10
print(result)
# Output: [11 12 13 14 15]


[11 12 13 14 15]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Element-wise subtraction
result = arr - 2
print(result)
# Output: [-1  0  1  2  3]


[-1  0  1  2  3]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Element-wise multiplication
result = arr * 3
print(result)
# Output: [ 3  6  9 12 15]


[ 3  6  9 12 15]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Element-wise division
result = arr / 2
print(result)
# Output: [0.5 1.  1.5 2.  2.5]


[0.5 1.  1.5 2.  2.5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Element-wise exponentiation
result = arr ** 2
print(result)
# Output: [ 1  4  9 16 25]


[ 1  4  9 16 25]


**type()**
In NumPy, arrays are represented by the numpy.ndarray class. When you create a NumPy array, it is an instance of this class. You can use the type() function to check the type of a NumPy array.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(type(arr))  # Output: <class 'numpy.ndarray'>


<class 'numpy.ndarray'>


**'size' attribute**


In NumPy, you can get the size of an array (i.e., the total number of elements in the array) using the size attribute of the array.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3]])

# Get the size of the array
arr_size = arr.size
print(arr_size)


3


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Get the size of the array
arr_size = arr.size
print(arr_size)  # Output: 6


6


**understanding Dimensions**

**axis**

In NumPy, the term "axis" refers to a specific dimension of an array. Each axis is identified by an integer, starting from 0 for the first axis. For example, in a 2D array (matrix), axis 0 refers to the rows, and axis 1 refers to the columns.

Consider a 2D array [[1, 2, 3], [4, 5, 6]]:

Axis 0 (rows): [1, 2, 3] and [4, 5, 6]
Axis 1 (columns): [1, 4], [2, 5], [3, 6]
Here's a breakdown of the axes for arrays of different dimensions:

For a 1D array, there is only one axis (axis 0), representing the elements along that axis.
For a 2D array, axis 0 represents the rows, and axis 1 represents the columns.
For arrays with more than 2 dimensions, each additional dimension adds a new axis.

**dimension**

The dimension of an array in NumPy refers to the number of axes or directions along which the array extends. Each axis is also called a dimension. Here are some simple examples to illustrate dimensions:

**0-Dimensional Array (Scalar):**

An array with zero dimensions is called a scalar. It represents a single value.

In [ ]:
import numpy as np

arr = np.array(42)  # 0-dimensional array
print(arr)
print("Dimensions:", arr.ndim)  # Output: 0


42
Dimensions: 0


**1-Dimensional Array (Vector):**

An array with one dimension is like a list of values. It has a single axis.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])  # 1-dimensional array
print(arr)
print("Dimensions:", arr.ndim)  # Output: 1


[1 2 3 4 5]
Dimensions: 1


**2-Dimensional Array (Matrix):**
An array with two dimensions represents a matrix with rows and columns.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])  # 2-dimensional array
print(arr)
print("Dimensions:", arr.ndim)  # Output: 2


[[1 2 3]
 [4 5 6]]
Dimensions: 2


**'shape' attribute**

In NumPy, the shape attribute of an array gives the dimensions of the array. It is a tuple of integers indicating the size of the array along each dimension. For example, for a 2D array (matrix) with 3 rows and 4 columns, the shape would be (3, 4).

In [8]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # Output: (2, 3)


(2, 3)


In this example, arr has 2 rows and 3 columns, so arr.shape returns (2, 3). This means arr is a 2D array with 2 rows and 3 columns.

The shape attribute is useful for understanding the structure of an array and for performing operations that depend on the array's dimensions.

Here are some more examples of using the shape attribute with NumPy arrays:

**1D Array (Vector):**

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)  # Output: (5,)


(5,)


In NumPy, the shape attribute of an array always returns a tuple representing the dimensions of the array. For a 1D array, the shape tuple contains a single element, which is the number of elements in the array. However, to differentiate between a 1D array and a scalar value (which also has a shape but is considered 0D), NumPy includes a comma after the number of elements to indicate that it is a tuple and not just an integer.