<a href="https://colab.research.google.com/github/pnggkkm/Python-Programming/blob/main/Creating_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems.
 It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.


A NumPy array is a powerful data structure provided by the NumPy library in Python. It is used to store and manipulate large arrays of numerical data efficiently. Here are some key features of NumPy arrays:

Efficient Storage: NumPy arrays are more memory-efficient than Python lists, especially for large arrays of data. This efficiency is achieved through the use of contiguous blocks of memory.
Fast Operations: NumPy provides a large set of functions and operations that can be applied directly to arrays, allowing for fast and efficient computation. These operations are implemented in C, which is much faster than Python's native operations.
Multidimensional: NumPy arrays can have multiple dimensions, allowing you to work with matrices and higher-dimensional data structures easily. This makes NumPy particularly useful for scientific computing and data analysis.
Broadcasting: NumPy arrays support broadcasting, which allows you to perform operations on arrays of different shapes. NumPy automatically handles the broadcasting by making copies of the smaller array to match the shape of the larger array.
Indexing and Slicing: NumPy arrays support advanced indexing and slicing operations, allowing you to extract and manipulate subsets of the array efficiently.
Vectorized Operations: NumPy arrays support vectorized operations, which means that you can apply operations to entire arrays at once, rather than looping over individual elements. This leads to faster and more concise code.

**Scalar**
A scalar quantity is a quantity that can be defined by its magnitude (or numerical value ) alone.
Examples of scalars are volume, density, speed, energy, mass

**Creating an array with scalar**

In NumPy, you can create an array from a scalar (single value) using the numpy.array() function. Here's how you can do it:

In [3]:
import numpy as np

arr = np.array(42)

print(arr)

42


In this example, the numpy.array() function takes a scalar value (scalar_value) and creates a NumPy array with that value. The resulting array will have the same data type as the input scalar.

**Creating a Single Dimensional array**
A single-dimensional array, often simply called a "1D array," is a fundamental data structure in programming that stores a collection of elements of the same data type in a linear sequence. In Python, the NumPy library provides a powerful implementation of 1D arrays through its numpy.array class.

**Method 1** Conversion from other Python structures (i.e. lists and tuples)

**Key features of 1D arrays include:**

**Homogeneous Data:** All elements in a 1D array must be of the same data type, unlike Python lists, which can hold elements of different types.
Fixed Size: Once created, the size of a 1D array is fixed and cannot be changed. You can't directly append or remove elements; instead, you create a new array with the desired elements.

**Efficient Storage:** NumPy's 1D arrays are more memory-efficient than Python lists, especially for large arrays, due to the use of contiguous blocks of memory.

**Vectorized Operations:**NumPy arrays support vectorized operations, allowing you to perform element-wise operations on the entire array without the need for explicit loops.
Indexing and Slicing: You can access individual elements or slices of a 1D array using square brackets, similar to Python lists.

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [4]:
import numpy as np

# Create a tuple
tuple_data = (1, 2, 3, 4, 5)

# Create a NumPy array from the tuple
array_from_tuple = np.array(tuple_data)

# Print the array
print(array_from_tuple)


[1 2 3 4 5]


**dtype Parameter**
You can create a NumPy array with a specific data type using the dtype parameter in the numpy.array() function. Here's an example:

In [6]:
import numpy as np

# Create an array with a specified data type (float32 in this case)
arr = np.array([1, 2, 3, 4, 5], dtype=np.float32)

# Print the array and its data type
print(arr)
print("Data type:", arr.dtype)


[1. 2. 3. 4. 5.]
Data type: float32


**Creating a 2 Dimensional Array**


In [7]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


creates a 2D NumPy array (matrix) arr with 2 rows and 3 columns, filled with the values [[1, 2, 3], [4, 5, 6]]

**Three Dimensional Array**

A three-dimensional (3D) array, also known as a tensor, is a data structure that stores values in a three-dimensional grid. An array that has 2-D arrays (matrices) as its elements is called 3-D array. In NumPy, you can create and manipulate 3D arrays using the numpy.array() function.

In [8]:
import numpy as np

# Create a 3D array
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Print the array
print(arr_3d)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**using np.zeros() to create arrays**


In [9]:
import numpy as np

# Create a 1D array filled with zeros of length 5
zeros_array = np.zeros(5)

# Print the array
print(zeros_array)


[0. 0. 0. 0. 0.]


In [10]:
import numpy as np

# Create a 2D array filled with zeros
zeros_array = np.zeros((3, 4))

# Print the array
print(zeros_array)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


The NumPy function np.zeros((3,4)) creates a 2D array (matrix) filled with zeros. The argument (3,4) specifies the shape of the array, where 3 is the number of rows and 4 is the number of columns. Here's how you can create and print this array:

The **np.ones()** function in NumPy is used to create an array filled with ones. It can be used to create arrays of any dimension (1D, 2D, 3D, etc.) with all elements initialized to 1. The function takes the desired shape of the array as an argument. Here are some examples:

**Creating a 1D array filled with ones:**

In [11]:
import numpy as np

# Create a 1D array with 5 elements, all initialized to 1
ones_array_1d = np.ones(5)

# Print the array
print(ones_array_1d)


[1. 1. 1. 1. 1.]


**Creating a 2D array filled with ones:**

In [12]:
import numpy as np

# Create a 2D array with 2 rows and 3 columns, all initialized to 1
ones_array_2d = np.ones((2, 3))

# Print the array
print(ones_array_2d)


[[1. 1. 1.]
 [1. 1. 1.]]


**Creating a 3D array filled with ones:**

In [13]:
import numpy as np

# Create a 3D array with shape (2, 3, 4), all initialized to 1
ones_array_3d = np.ones((2, 3, 4))

# Print the array
print(ones_array_3d)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


**np.arange()**
np.arange() is a NumPy function used to create an array containing evenly spaced values within a specified range. It is similar to Python's built-in range() function but returns an array instead of a list. The np.arange() function takes the start, stop, and step size as arguments and generates values from the start value up to (but not including) the stop value, with the specified step size.

Here's the basic syntax of np.arange():

In [14]:
import numpy as np

# Syntax: np.arange(start, stop, step)
# Generates values from start to stop (exclusive) with the specified step
arr = np.arange(0, 10, 2)  # Generates values from 0 to 10 (exclusive) with a step of 2
print(arr)  # Output: [0 2 4 6 8]


[0 2 4 6 8]


In this example, np.arange(0, 10, 2) creates an array with values [0, 2, 4, 6, 8], starting from 0, up to (but not including) 10, with a step size of 2.

You can also use np.arange() with a single argument to generate values from 0 up to (but not including) the specified number with a default step size of 1:

In [15]:
arr = np.arange(5)  # Equivalent to np.arange(0, 5, 1)
print(arr)  # Output: [0 1 2 3 4]


[0 1 2 3 4]


**np.linspace()**
np.linspace() is another NumPy function used to create an array of evenly spaced numbers over a specified interval. Unlike np.arange(), which generates values with a specified step size, np.linspace() generates values with a specified number of points within the interval.

Here's the basic syntax of np.linspace():

In [17]:
import numpy as np

# Syntax: np.linspace(start, stop, num)
# Generates 'num' evenly spaced values from start to stop (inclusive)
#arr = np.linspace(start, stop, num)

# Example:
arr = np.linspace(0, 2, 9)  # Generates 9 values from 0 to 2 (inclusive)
print(arr)  # Output: [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2. ]


[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [21]:
import numpy as np

arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


np.linspace() is particularly useful when you need a specific number of points within an interval, such as when plotting functions or generating test data for numerical simulations.

**np.full()**
np.full() is a NumPy function used to create an array filled with a specified value. It takes the shape of the desired array and the fill value as arguments and returns a new array with the specified shape and filled with the specified value.

Here's the basic syntax of np.full():

In [22]:
import numpy as np

# Syntax: np.full(shape, fill_value)
# Creates a new array with the specified shape and filled with the specified value
#arr = np.full(shape, fill_value)

# Example:
arr = np.full((3, 4), 5)  # Creates a 3x4 array filled with the value 5
print(arr)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In this example, np.full((3, 4), 5) creates a 3x4 array filled with the value 5.

For a single-dimensional array, np.full() works similarly but with a single integer argument specifying the length of the array instead of a tuple for shape. Here's how you would use np.full() to create a 1D array:

In [23]:
import numpy as np

# Syntax: np.full(length, fill_value)
# Creates a new 1D array with the specified length and filled with the specified value
arr = np.full(5, 10)  # Creates a 1D array of length 5 filled with the value 10
print(arr)


[10 10 10 10 10]


In this example, np.full(5, 10) creates a 1D array of length 5 filled with the value 10. The resulting array is [10 10 10 10 10].

**np.eye()**


np.eye() is a NumPy function used to create a 2D array (matrix) with ones on the diagonal and zeros elsewhere, often called an identity matrix. It takes a single integer argument N and returns an N x N identity matrix.

Here's the basic syntax of np.eye():

In [ ]:
import numpy as np

# Syntax: np.eye(N)
# Creates an N x N identity matrix
#arr = np.eye(N)

# Example:
arr = np.eye(3)  # Creates a 3x3 identity matrix
print(arr)



**np.empty()**

np.empty() is a NumPy function that creates an array without initializing its values. The function takes the shape of the array as an argument and returns a new array with uninitialized values. The values in the array are not set to any particular initial value and will depend on the state of the memory at the time the array is created. It is important to note that the np.empty() function does not guarantee that the array will be filled with zeros or any other specific value.

In [2]:
import numpy as np

# Syntax: np.empty(shape)
# Creates a new array with the specified shape without initializing its values
# Example:
arr = np.empty((2, 3))  # Creates a 2x3 array without initializing its values
print(arr)


[[4.89167785e-310 0.00000000e+000 2.05833592e-312]
 [6.79038654e-313 2.14321575e-312 2.27053550e-312]]


In this example, np.empty((2, 3)) creates a 2x3 array without initializing its values. The values in the array will depend on the state of the memory at the time the array is created and may not be predictable or meaningful.